#Basic Workflow
name : CI

# Controls when the workflow will run
on:
#Triggers the workflow on push events only main branch
  push:
    branches:[ main ]

#Next step : Jobs
  #A workflow run is made up of one or more jobs that can run sequentially or parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    #The type of runner that the job will run
    runs-on:  ubuntu-latest # THe identatio is important

    strategy:
    matrix:
      node-version: [16.x] #Nodejs enviroment version
    
    #Steps Represent a sequence of tasks that will be executed as part of the job
    steps:
      #Checks-out your repository under $GITHUB_WORKSPACE, so your joc can access it 
    - name: Checkout reposotory 
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{matrix.node-version}}

    - name: Install dependencies
      run : npm install

    - name: Run the tests 
      run: npm test

    - name : Build Page
      run : npm run build
    
    - name : Deploy to gh-pages
      uses : |
              git config --global user.name ${{secrets.user_name}}
              git config --global user.email ${{secrets.user_email}}
              git remote set-url origin https://${{secrets.my_tokenPersonal}}@github.com/${{secrets.repository}}.git
              npm run deploy

      



  




