version: "3.9"  
services:
  ansible:
    build: 
      context: ./ansibleBase
      dockerfile: Dockerfile
    container_name: AController
    volumes:
      - type: bind
        source: ./ansibleFiles
        target: /home/ansible_controller/ansibleFiles


networks:
  default:
    driver: overlay
    name: hello-world_default
    external: true
    