version: "3.9"  
services:

  hello-world:
    container_name: hello-world
    build:
      context: ./hello-world
    ports:
      - "3000:3000" # Local Machine / Container App port

  ansible:
    build: 
      context: ./ansible_controller/ansibleBase
      dockerfile: Dockerfile
    container_name: AController
    volumes: #Volumes
      - type: bind
        source: ./ansible_controller/ansibleFiles
        target: /home/aController/ansibleFiles