#Basic Workflow
name: CI_actionsCarlos

# Controls when the workflow will run
on:
#Triggers the workflow on push events only main branch
  push:
    branches: [ main ]
  
#Next step : Jobs
  #A workflow run is made up of one or more jobs that can run sequentially or parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    #The type of runner that the job will run
    runs-on:  ubuntu-latest # THe identatio is important    

    strategy:
      matrix:
        node-version: [16.x] #Nodejs enviroment version

    #adding working-directory to .env   
    env:
      working-directory: ./capstone_project/hello-world    

    defaults:
      run:
        working-directory: ./capstone_project/hello-world    
    
    #Steps Represent a sequence of tasks that will be executed as part of the job
    steps:
      #Checks-out your repository under $GITHUB_WORKSPACE, so your joc can access it 
      - name: Checkout reposotory #Name for the action
        uses: actions/checkout@v2 #Action be will to do --this action check if there 

      - name: Set up Node.js ${{ matrix.node-version }} #Name for the action
        uses: actions/setup-node@v2 #This action setup the enviroment 
        with:
          node-version: ${{matrix.node-version}} #Version for the action of enviroment

      - name: Install dependencies 
        run : npm install #This action install the packages
        #working-directory: ${{env.working-directory}} #Setting the directory for the run the script

      - name: Run the tests 
        run: npm test #This action test the app
        #working-directory: ${{env.working-directory}} #Setting the directory for the run the script

      - name : Build Page
        run : npm run build
        #working-directory: ${{env.working-directory}}

      #- name: deploy/build
        #run : npm run deploy
      
      - name : Deploy to gh-pages                 
        uses: JamesIves/github-pages-deploy-action@v4.2.2        
        with:
          branches: gh-pages # The branch the action should deploy to.
          folder: build # The folder the action should deploy.
        
        # run: |
        #         git config --global user.name ${{ secrets.user_name}}
        #         git config --global user.email ${{ secrets.user_email }}
        #         git remote set-url origin https://${{secrets.my_tokenPersonal}}@github.com/${{secrets.repository}}.git
        #         npm run deploy
        
          


        



  




