#Basic Workflow
name: CI_actionsCarlos

# Controls when the workflow will run
on:
#Triggers the workflow on push events only main branch
  push:
    branches: [ main ]
  
#Next step : Jobs
  #A workflow run is made up of one or more jobs that can run sequentially or parallel
jobs:
  # This workflow contains a single job called "deploy"  
  setup_Node_ENV:   

  #The type of runner that the job will run
    runs-on: ubuntu-latest # THe identatio is important    

    strategy:
      matrix:
        node-version: [16.x] #Nodejs enviroment version

      #adding working-directory to .env   
    env:
      working-directory: ./capstone_project/hello-world    

    defaults:
      run:
        working-directory: ./capstone_project/hello-world    
      
    #Steps Represent a sequence of tasks that will be executed as part of the job
    steps:
      #Checks-out your repository under $GITHUB_WORKSPACE, so your joc can access it 
      - name: Checkout reposotory #Name for the action
        uses: actions/checkout@v2 #Action be will to do --this action check if there 

      - name: Set up Node.js ${{ matrix.node-version }} #Name for the action
        uses: actions/setup-node@v2 #This action setup the enviroment 
        with:
          node-version: ${{matrix.node-version}} #Version for the action of enviroment

      - name: Install dependencies 
        run : npm install #This action install the packages
        #working-directory: ${{env.working-directory}} #Setting the directory for the run the script

      - name: Run the tests 
        run: npm test #This action test the app
        #working-directory: ${{env.working-directory}} #Setting the directory for the run the script

      # - name : Build Page
      #   run : npm run predeploy
      #   #working-directory: ${{env.working-directory}}

      #   #- name: deploy/build
      #   #run : npm run deploy
      
      # - name : Deploy to gh-pages                 
      #   uses: peaceiris/actions-gh-pages@v3        #This is the best in the marketplace
      #   with:
      #     github_token: ${{secrets.MY_TOKENPERSONAL}}
      #     publish_dir: ./build # The folder the action should deploy.        
    
  deploying:      

    runs-on:  ubuntu-latest # THe identatio is important    

    strategy:
      matrix:
        node-version: [16.x] #Nodejs enviroment version

    defaults:
      run:
        working-directory: ./capstone_project/hello-world  #directory target    

      
      #Steps Represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Set up Node.js ${{ matrix.node-version }} #Name for the action
        uses: actions/setup-node@v2 #This action setup the enviroment 
        with:
          node-version: ${{matrix.node-version}} #Version for the action of enviroment

      - name : Build Page
        run : npm run predeploy
          #working-directory: ${{env.working-directory}}

          #- name: deploy/build
            #run : npm run deploy
        
      - name : Deploy to gh-pages                 
        uses: peaceiris/actions-gh-pages@v3        #This is the best in the marketplace
        with:
          github_token: ${{secrets.MY_TOKENPERSONAL}}
          publish_dir: ./build # The folder the action should deploy.        
              
              
                


              



        




